# Generated by Django 6.0.4 on 2026-05-18 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_estudio_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('semestre', models.PositiveSmallIntegerField(default=1)),
                ('carrera', models.CharField(choices=[('sistemas', 'Ingeniería de Sistemas'), ('civil', 'Ingeniería Civil'), ('industrial', 'Ingeniería Industrial'), ('otra', 'Otra')], default='sistemas', max_length=30)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='codigo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='materia',
            name='semestre',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='materia',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud_app.materiabase'),
        ),
    ]
