# Generated by Django 6.0.4 on 2026-05-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_materiabase_materia_codigo_materia_semestre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiabase',
            name='carrera',
            field=models.CharField(choices=[('sistemas', 'Ingeniería de Sistemas'), ('derecho', 'Derecho'), ('psicologia', 'Psicología'), ('contaduria', 'Contaduría Pública'), ('administracion', 'Administración de Empresas'), ('enfermeria', 'Enfermería')], default='sistemas', max_length=30),
        ),
    ]
