# Generated by Django 6.0.4 on 2026-05-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_alter_materiabase_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
    ]
