# Generated by Django 6.0.4 on 2026-05-20 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0005_remove_tarea_fecha_entrega_tarea_fecha_programada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.tarea')),
            ],
        ),
    ]
